---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-chaos
  namespace: #{INFRA_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-chaos-infra-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infra-cluster-role
subjects:
  - kind: ServiceAccount
    name: argo-chaos
    namespace: #{INFRA_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-chaos-ops-role-binding
  namespace: #{INFRA_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-ops-role
subjects:
  - kind: ServiceAccount
    name: argo-chaos
    namespace: #{INFRA_NAMESPACE}